# Generated by Django 6.0.7 on 2026-08-25 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('citizen', 'Citizen'), ('authority', 'Authority')], default='citizen', max_length=20)),
                ('department', models.CharField(blank=True, choices=[('garbage', 'Garbage'), ('water', 'Water'), ('animal', 'Animal/Pet Control'), ('roads', 'Roads'), ('electricity', 'Electricity'), ('traffic', 'Traffic'), ('other', 'Other')], max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
