# Generated by Django 5.2.17 on 2026-08-30 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_comment_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ai_priority_suggested',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='What the AI suggested, for transparency vs. the final priority chosen.', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='department',
            field=models.CharField(blank=True, help_text='Auto-routed by AI based on category.', max_length=80),
        ),
        migrations.AddField(
            model_name='report',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, help_text='Set by AI duplicate detection if a very similar nearby report already exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='reports.report'),
        ),
    ]
