# Generated by Django 6.0.7 on 2026-08-31 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_userprofile'),
        ('reports', '0003_ai_fields'),
    ]

    operations = [
    ]
